services:
  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      # Volume Docker pour persister les modèles téléchargés
      - ollama_models:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_TEXT_MODEL=godotai
      - NVIDIA_VISIBLE_DEVICES=all
    restart: unless-stopped
    devices:
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia0:/dev/nvidia0
    # Limite ou augmente le CPU (ici 4 vCPU)
    cpus: 8.0

volumes:
  ollama_models:
