name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches: [AIAGENT]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material mkdocs-d2-plugin
          D2_VERSION=v0.7.0
          curl -L https://github.com/terrastruct/d2/releases/download/$D2_VERSION/d2-$D2_VERSION-linux-amd64.tar.gz -o d2.tar.gz
          tar -xzf d2.tar.gz
          sudo mv d2-$D2_VERSION/bin/d2 /usr/local/bin/d2
      - name: Build docs
        run: mkdocs build
      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mkdocs gh-deploy --force --clean
